export { default as BasicInfo } from './BasicInfo'
export { default as Survey } from './Survey'
export { default as Timetable } from './Timetable'
export { default as Pretrain } from './Pretrain'
export { default as Workupload } from './Workupload'
export { default as Discuss } from './Discuss'
export { default as Report } from './Report'
export { default as Invitation } from './Invitation'
